In [1]:
conda list

# packages in environment at /home/aki/anaconda3/envs/hands-on_ML:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
absl-py                   0.14.1                   pypi_0    pypi
argon2-cffi               20.1.0           py39h27cfd23_1  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     21.2.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
bleach                    4.0.0              pyhd3eb1b0_0  
ca-certificates           2021.9.30            h06a4308_1  
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.5.30        py39h06a4308_0  
cffi                      1.14.6           py39h400218f_0  
charset-normalizer        2.0.7                    pypi_0    pypi
clang 


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0 ,6.0])

In [5]:
x + y

array([3., 6., 9.])

In [6]:
x - y

array([-1., -2., -3.])

In [7]:
x * y

array([ 2.,  8., 18.])

In [8]:
x / 2.0

array([0.5, 1. , 1.5])

In [9]:
y/ 2.0

array([1., 2., 3.])

In [20]:
x - 10

array([-9., -8., -7.])

In [10]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [11]:
A.shape

(2, 2)

In [12]:
A.dtype

dtype('int64')

In [13]:
B = np.array([[3,0], [0,6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [14]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [15]:
A = np.array([[1,2], [3,4]])
B = np.array([10,20])

In [16]:
A

array([[1, 2],
       [3, 4]])

In [17]:
B

array([10, 20])

In [18]:
A * B

array([[10, 40],
       [30, 80]])

形状の異なる配列同士の演算が出来る → numpyのブロードキャスト機能

要素へのアクセス

In [22]:
X = np.array([[51, 55], [13, 76], [32, 98]])
print(X)

[[51 55]
 [13 76]
 [32 98]]


In [23]:
X[0]

array([51, 55])

In [24]:
X[0][1]

55

In [25]:
X[2][0]

32

In [28]:
# for文で要素一つずつ取得できる
for row in X:
    print(row)

[51 55]
[13 76]
[32 98]
